name: springboot-aws-webservice CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

permissions:
  contents: read

jobs:
  build:
    # 실행 환경
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: springboot-aws-webservice
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      OCI_CLI_BUCKET: ${{ secrets.OCI_CLI_BUCKET }}

    # Task의 sequence
    steps:
    # 저장소로 코드 내려받기
    - uses: actions/checkout@v3
    # MySQL 세팅
    - name: verify MySQL connection from host
      run: |
        sudo service mysql start
        mysql -uroot -proot --host=localhost -e "CREATE DATABASE springaws"
        mysql -uroot -proot --host=localhost -e "create user springaws identified by 'springaws'"
        mysql -uroot -proot --host=localhost -e "grant all privileges on springaws.* to springaws"
        sudo service mysql restart
    # JDK17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    # gradlew 권한 설정(execute)
    - name: Run chmod to make gradle executable
      run: chmod +x ./gradlew
    # gradle build
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: build
    # jar 파일 이동
    - name: Move jar file to root
      run: |
        pwd
        cd build/libs
        BUILD_JAR_FILE_NAME=$(echo *.jar)
        BUILD_JAR_FILE_NAME=$(echo ${BUILD_JAR_FILE_NAME%%.jar})
        PUT_JAR_FILE_NAME=${BUILD_JAR_FILE_NAME}_run_${{ github.run_number }}_attempt_${{ github.run_attempt }}
        echo "PUT_JAR_FILE_NAME=${PUT_JAR_FILE_NAME}" >> $GITHUB_ENV
        mv ${BUILD_JAR_FILE_NAME}.jar /home/runner/work/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}/${PUT_JAR_FILE_NAME}.jar
    # jar 파일 OCI Object Storage에 업로드
    - name: Upload jar to OCI Object Storage
      uses: oracle-actions/run-oci-cli-command@v1.1.1
      with:
        command: "os object put -bn ${{ env.OCI_CLI_BUCKET }} --file ${{ env.PUT_JAR_FILE_NAME }}.jar --no-overwrite"

    # 개발 서버로 jar 파일 전송
    - name: Transfer jar file
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        overwrite: true
        source: "${{ env.PUT_JAR_FILE_NAME }}.jar"
        target: 'workspace/build'

    # 개발 서버에서 deploy.sh 실행
    - name: Run deploy.sh
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd workspace/scripts
          ./stop.sh
          ./start.sh ${{ env.PUT_JAR_FILE_NAME }}.jar
          ./health.sh
