# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: springboot-aws-webservice CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    # 실행 환경
    runs-on: ubuntu-latest

    # Task의 sequence
    steps:
    - uses: actions/checkout@v3
    - name: verify MySQL connection from host
      run: |
        sudo service mysql start
        mysql -uroot -proot --host=localhost -e "CREATE DATABASE springaws"
        mysql -uroot -proot --host=localhost -e "create user springaws identified by 'springaws'"
        mysql -uroot -proot --host=localhost -e "grant all privileges on springaws.* to springaws"
        sudo service mysql restart

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        
    - name: Run chmod to make gradle executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: build
